# Generated by Django 3.2.5 on 2021-07-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_favouritem_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupm',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
