# Generated by Django 3.2.5 on 2021-08-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_favouritem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupm',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
