# Generated by Django 3.2.5 on 2021-08-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_signupm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritem',
            name='prices',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
