# Generated by Django 3.2.5 on 2021-08-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_favouritem_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritem',
            name='prices',
        ),
    ]
